var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,k="undefined"!=typeof WorkerGlobalScope,m="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,n="./this.program",p=(a,b)=>{throw b;},r="",t,u;
if(m){var fs=require("fs");require("path");r=__dirname+"/";u=a=>{a=v(a)?new URL(a):a;return fs.readFileSync(a)};t=async a=>{a=v(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(n=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);p=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||k)k?r=self.location.href:"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src),r=r.startsWith("blob:")?"":r.slice(0,
r.replace(/[?#].*/,"").lastIndexOf("/")+1),k&&(u=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),t=async a=>{if(v(a))return new Promise((d,c)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?d(f.response):c(f.status)};f.onerror=c;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var w=console.log.bind(console),x=console.error.bind(console),y,z,A=!1,B,C,D,E,v=a=>a.startsWith("file://");function F(){var a=z.buffer;new Int8Array(a);new Int16Array(a);e.HEAPU8=B=new Uint8Array(a);new Uint16Array(a);C=new Int32Array(a);D=new Uint32Array(a);new Float32Array(a);new Float64Array(a);E=new BigInt64Array(a);new BigUint64Array(a)}var G=0,H=null;
function I(a){e.onAbort?.(a);a="Aborted("+a+")";x(a);A=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var J;async function ba(a){if(!y)try{var b=await t(a);return new Uint8Array(b)}catch{}if(a==J&&y)a=new Uint8Array(y);else if(u)a=u(a);else throw"both async and sync fetching of the wasm failed";return a}async function ca(a,b){try{var d=await ba(a);return await WebAssembly.instantiate(d,b)}catch(c){x(`failed to asynchronously prepare wasm: ${c}`),I(c)}}
async function ea(a){var b=J;if(!y&&"function"==typeof WebAssembly.instantiateStreaming&&!v(b)&&!m)try{var d=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(c){x(`wasm streaming compile failed: ${c}`),x("falling back to ArrayBuffer instantiation")}return ca(b,a)}class fa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var M=a=>{for(;0<a.length;)a.shift()(e)},N=[],O=[],ha=()=>{var a=e.preRun.shift();O.push(a)},P=!0;class ia{constructor(a){this.A=a-24}}
var Q=0,ja=0,R="undefined"!=typeof TextDecoder?new TextDecoder:void 0,ka=(a,b=0,d=NaN)=>{var c=b+d;for(d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&R)return R.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},
S=(a,b,d)=>{var c=B;if(!(0<d))return 0;var f=b;d=b+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(b>=d)break;c[b++]=h}else{if(2047>=h){if(b+1>=d)break;c[b++]=192|h>>6}else{if(65535>=h){if(b+2>=d)break;c[b++]=224|h>>12}else{if(b+3>=d)break;c[b++]=240|h>>18;c[b++]=128|h>>12&63}c[b++]=128|h>>6&63}c[b++]=128|h&63}}c[b]=0;return b-f},T={},la=()=>{if(!U){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",
HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:n||"./this.program"},b;for(b in T)void 0===T[b]?delete a[b]:a[b]=T[b];var d=[];for(b in a)d.push(`${b}=${a[b]}`);U=d}return U},U,ma=[null,[],[]],V=[],W,X,na=[];e.noExitRuntime&&(P=e.noExitRuntime);e.print&&(w=e.print);e.printErr&&(x=e.printErr);e.wasmBinary&&(y=e.wasmBinary);e.thisProgram&&(n=e.thisProgram);
e.addFunction=(a,b)=>{if(!X){X=new WeakMap;var d=W.length;if(X)for(var c=0;c<0+d;c++){var f;(f=V[c])||(V[c]=f=W.get(c));f&&X.set(f,c)}}if(d=X.get(a)||0)return d;if(na.length)d=na.pop();else{try{W.grow(1)}catch(q){if(!(q instanceof RangeError))throw q;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}d=W.length-1}try{c=d,W.set(c,a),V[c]=W.get(c)}catch(q){if(!(q instanceof TypeError))throw q;if("function"==typeof WebAssembly.Function){var g=WebAssembly.Function;c={i:"i32",j:"i64",f:"f32",d:"f64",
e:"externref",p:"i32"};f={parameters:[],results:"v"==b[0]?[]:[c[b[0]]]};for(var h=1;h<b.length;++h)f.parameters.push(c[b[h]]);b=new g(f,a)}else{c=[1];f=b.slice(0,1);b=b.slice(1);h={i:127,p:127,j:126,f:125,d:124,e:111};c.push(96);var l=b.length;128>l?c.push(l):c.push(l%128|128,l>>7);for(g of b)c.push(h[g]);"v"==f?c.push(0):c.push(1,h[f]);b=[0,97,115,109,1,0,0,0,1];g=c.length;128>g?b.push(g):b.push(g%128|128,g>>7);b.push(...c);b.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));
b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f}g=d;W.set(g,b);V[g]=W.get(g)}X.set(a,d);return d};e.UTF8ToString=(a,b)=>a?ka(B,a,b):"";
var oa={a:(a,b,d)=>{var c=new ia(a);D[c.A+16>>2]=0;D[c.A+4>>2]=b;D[c.A+8>>2]=d;Q=a;ja++;throw Q;},d:function(){return 0},m:function(){return 0},n:function(){},j:()=>I(""),k:(a,b,d,c)=>{var f=(new Date).getFullYear(),g=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();D[a>>2]=60*Math.max(g,f);C[b>>2]=Number(g!=f);b=h=>{var l=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(g);b=b(f);f<g?(S(a,d,17),S(b,
c,17)):(S(a,c,17),S(b,d,17))},e:function(a,b,d){if(!(0<=a&&3>=a))return 28;E[d>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},f:a=>{var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var c=b*(1+.2/d);c=Math.min(c,a+100663296);a:{c=(Math.min(2147483648,65536*Math.ceil(Math.max(a,c)/65536))-z.buffer.byteLength+65535)/65536|0;try{z.grow(c);F();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},h:(a,b)=>{var d=0,c=0,f;for(f of la()){var g=b+d;D[a+
c>>2]=g;d+=S(f,g,Infinity)+1;c+=4}return 0},i:(a,b)=>{var d=la();D[a>>2]=d.length;a=0;for(var c of d){for(var f=d=0;f<c.length;++f){var g=c.charCodeAt(f);127>=g?d++:2047>=g?d+=2:55296<=g&&57343>=g?(d+=4,++f):d+=3}a+=d+1}D[b>>2]=a;return 0},c:()=>52,l:()=>52,g:function(){return 70},b:(a,b,d,c)=>{for(var f=0,g=0;g<d;g++){var h=D[b>>2],l=D[b+4>>2];b+=8;for(var q=0;q<l;q++){var da=a,K=B[h+q],L=ma[da];0===K||10===K?((1===da?w:x)(ka(L)),L.length=0):L.push(K)}f+=l}D[c>>2]=f;return 0},o:a=>{P||(e.onExit?.(a),
A=!0);p(a,new fa(a))}},Y;(async function(){function a(d){Y=d.exports;z=Y.p;F();W=Y.z;G--;e.monitorRunDependencies?.(G);0==G&&H&&(d=H,H=null,d());return Y}G++;e.monitorRunDependencies?.(G);var b={a:oa};if(e.instantiateWasm)return new Promise(d=>{e.instantiateWasm(b,(c,f)=>{d(a(c,f))})});J??=e.locateFile?e.locateFile("cyth.wasm",r):r+"cyth.wasm";return a((await ea(b)).instance)})();e._memory_alloc=a=>(e._memory_alloc=Y.r)(a);e._free=a=>(e._free=Y.s)(a);e._cyth_wasm_init=a=>(e._cyth_wasm_init=Y.t)(a);
e._cyth_wasm_load_function=(a,b)=>(e._cyth_wasm_load_function=Y.u)(a,b);e._cyth_wasm_compile=(a,b)=>(e._cyth_wasm_compile=Y.v)(a,b);e._cyth_wasm_set_error_callback=a=>(e._cyth_wasm_set_error_callback=Y.w)(a);e._cyth_wasm_set_result_callback=a=>(e._cyth_wasm_set_result_callback=Y.x)(a);e._cyth_wasm_set_link_callback=a=>(e._cyth_wasm_set_link_callback=Y.y)(a);
function Z(){function a(){e.calledRun=!0;if(!A){Y.q();e.onRuntimeInitialized?.();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();N.push(b)}M(N)}}if(0<G)H=Z;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)ha();M(O);0<G?H=Z:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);a()},1)):a()}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();Z();
