var c;c||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,k="undefined"!=typeof WorkerGlobalScope,m="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,n="./this.program",p=(a,b)=>{throw b;},r="",t,u;
if(m){var fs=require("fs");require("path");r=__dirname+"/";u=a=>{a=v(a)?new URL(a):a;return fs.readFileSync(a)};t=async a=>{a=v(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(n=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=c);p=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||k)k?r=self.location.href:"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src),r=r.startsWith("blob:")?"":r.slice(0,
r.replace(/[?#].*/,"").lastIndexOf("/")+1),k&&(u=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),t=async a=>{if(v(a))return new Promise((e,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?e(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var w=console.log.bind(console),x=console.error.bind(console),y,z,A=!1,B,C,D,E,F,v=a=>a.startsWith("file://");function G(){var a=z.buffer;new Int8Array(a);new Int16Array(a);c.HEAPU8=C=new Uint8Array(a);new Uint16Array(a);D=new Int32Array(a);E=new Uint32Array(a);new Float32Array(a);new Float64Array(a);F=new BigInt64Array(a);new BigUint64Array(a)}var H=0,I=null;
function J(a){c.onAbort?.(a);a="Aborted("+a+")";x(a);A=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var K;async function ba(a){if(!y)try{var b=await t(a);return new Uint8Array(b)}catch{}if(a==K&&y)a=new Uint8Array(y);else if(u)a=u(a);else throw"both async and sync fetching of the wasm failed";return a}async function ca(a,b){try{var e=await ba(a);return await WebAssembly.instantiate(e,b)}catch(d){x(`failed to asynchronously prepare wasm: ${d}`),J(d)}}
async function da(a){var b=K;if(!y&&"function"==typeof WebAssembly.instantiateStreaming&&!v(b)&&!m)try{var e=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(e,a)}catch(d){x(`wasm streaming compile failed: ${d}`),x("falling back to ArrayBuffer instantiation")}return ca(b,a)}class L{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ea=a=>{for(;0<a.length;)a.shift()(c)},fa=[],ha=[],ia=()=>{var a=c.preRun.shift();ha.push(a)},M=!0,ja="undefined"!=typeof TextDecoder?new TextDecoder:void 0,N=(a,b=0,e=NaN)=>{var d=b+e;for(e=b;a[e]&&!(e>=d);)++e;if(16<e-b&&a.buffer&&ja)return ja.decode(a.subarray(b,e));for(d="";b<e;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=
65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d};class la{constructor(a){this.P=a-24}}
var ma=0,na=0,O=0,P={},oa=a=>{B=a;M||0<O||(c.onExit?.(a),A=!0);p(a,new L(a))},pa=a=>{if(!A)try{if(a(),!(M||0<O))try{B=a=B,oa(a)}catch(b){b instanceof L||"unwind"==b||p(1,b)}}catch(b){b instanceof L||"unwind"==b||p(1,b)}},Q=(a,b,e)=>{var d=C;if(!(0<e))return 0;var f=b;e=b+e-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(b>=e)break;d[b++]=h}else{if(2047>=h){if(b+1>=e)break;d[b++]=192|h>>6}else{if(65535>=
h){if(b+2>=e)break;d[b++]=224|h>>12}else{if(b+3>=e)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63}d[b++]=128|h>>6&63}d[b++]=128|h&63}}d[b]=0;return b-f},R={},qa=()=>{if(!U){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:n||"./this.program"},b;for(b in R)void 0===R[b]?delete a[b]:a[b]=R[b];var e=[];for(b in a)e.push(`${b}=${a[b]}`);U=e}return U},U,ra=[null,[],
[]],V=[],W,X,sa=[];c.noExitRuntime&&(M=c.noExitRuntime);c.print&&(w=c.print);c.printErr&&(x=c.printErr);c.wasmBinary&&(y=c.wasmBinary);c.thisProgram&&(n=c.thisProgram);
c.addFunction=(a,b)=>{if(!X){X=new WeakMap;var e=W.length;if(X)for(var d=0;d<0+e;d++){var f;(f=V[d])||(V[d]=f=W.get(d));f&&X.set(f,d)}}if(e=X.get(a)||0)return e;if(sa.length)e=sa.pop();else{try{W.grow(1)}catch(q){if(!(q instanceof RangeError))throw q;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}e=W.length-1}try{d=e,W.set(d,a),V[d]=W.get(d)}catch(q){if(!(q instanceof TypeError))throw q;if("function"==typeof WebAssembly.Function){var g=WebAssembly.Function;d={i:"i32",j:"i64",f:"f32",d:"f64",
e:"externref",p:"i32"};f={parameters:[],results:"v"==b[0]?[]:[d[b[0]]]};for(var h=1;h<b.length;++h)f.parameters.push(d[b[h]]);b=new g(f,a)}else{d=[1];f=b.slice(0,1);b=b.slice(1);h={i:127,p:127,j:126,f:125,d:124,e:111};d.push(96);var l=b.length;128>l?d.push(l):d.push(l%128|128,l>>7);for(g of b)d.push(h[g]);"v"==f?d.push(0):d.push(1,h[f]);b=[0,97,115,109,1,0,0,0,1];g=d.length;128>g?b.push(g):b.push(g%128|128,g>>7);b.push(...d);b.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));
b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f}g=e;W.set(g,b);V[g]=W.get(g)}X.set(a,e);return e};c.UTF8ToString=(a,b)=>a?N(C,a,b):"";
var ua={a:(a,b,e,d)=>J(`Assertion failed: ${a?N(C,a):""}, at: `+[b?b?N(C,b):"":"unknown filename",e,d?d?N(C,d):"":"unknown function"]),b:(a,b,e)=>{var d=new la(a);E[d.P+16>>2]=0;E[d.P+4>>2]=b;E[d.P+8>>2]=e;ma=a;na++;throw ma;},d:function(){return 0},g:function(){return 0},h:function(){},i:()=>J(""),k:()=>{M=!1;O=0},l:(a,b)=>{P[a]&&(clearTimeout(P[a].id),delete P[a]);if(!b)return 0;var e=setTimeout(()=>{delete P[a];pa(()=>ta(a,performance.now()))},b);P[a]={id:e,R:b};return 0},m:(a,b,e,d)=>{var f=(new Date).getFullYear(),
g=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();E[a>>2]=60*Math.max(g,f);D[b>>2]=Number(g!=f);b=h=>{var l=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(g);b=b(f);f<g?(Q(a,e,17),Q(b,d,17)):(Q(a,d,17),Q(b,e,17))},n:function(a,b,e){if(!(0<=a&&3>=a))return 28;F[e>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},o:a=>{var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var e=
1;4>=e;e*=2){var d=b*(1+.2/e);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-z.buffer.byteLength+65535)/65536|0;try{z.grow(d);G();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},q:(a,b)=>{var e=0,d=0,f;for(f of qa()){var g=b+e;E[a+d>>2]=g;e+=Q(f,g,Infinity)+1;d+=4}return 0},r:(a,b)=>{var e=qa();E[a>>2]=e.length;a=0;for(var d of e){for(var f=e=0;f<d.length;++f){var g=d.charCodeAt(f);127>=g?e++:2047>=g?e+=2:55296<=g&&57343>=g?(e+=4,++f):e+=3}a+=
e+1}E[b>>2]=a;return 0},c:()=>52,f:()=>52,p:function(){return 70},e:(a,b,e,d)=>{for(var f=0,g=0;g<e;g++){var h=E[b>>2],l=E[b+4>>2];b+=8;for(var q=0;q<l;q++){var ka=a,S=C[h+q],T=ra[ka];0===S||10===S?((1===ka?w:x)(N(T)),T.length=0):T.push(S)}f+=l}E[d>>2]=f;return 0},j:oa},Y;
(async function(){function a(e){Y=e.exports;z=Y.s;G();W=Y.z;H--;c.monitorRunDependencies?.(H);0==H&&I&&(e=I,I=null,e());return Y}H++;c.monitorRunDependencies?.(H);var b={a:ua};if(c.instantiateWasm)return new Promise(e=>{c.instantiateWasm(b,(d,f)=>{e(a(d,f))})});K??=c.locateFile?c.locateFile("cyth.wasm",r):r+"cyth.wasm";return a((await da(b)).instance)})();c._memory_alloc=a=>(c._memory_alloc=Y.u)(a);c._set_error_callback=a=>(c._set_error_callback=Y.v)(a);
c._set_result_callback=a=>(c._set_result_callback=Y.w)(a);c._run=(a,b)=>(c._run=Y.x)(a,b);c._free=a=>(c._free=Y.y)(a);c._BinaryenSizeofLiteral=()=>(c._BinaryenSizeofLiteral=Y.A)();c._BinaryenSizeofAllocateAndWriteResult=()=>(c._BinaryenSizeofAllocateAndWriteResult=Y.B)();c.__i32_store8=(a,b)=>(c.__i32_store8=Y.C)(a,b);c.__i32_store16=(a,b)=>(c.__i32_store16=Y.D)(a,b);c.__i32_store=(a,b)=>(c.__i32_store=Y.E)(a,b);c.__f32_store=(a,b)=>(c.__f32_store=Y.F)(a,b);
c.__f64_store=(a,b)=>(c.__f64_store=Y.G)(a,b);c.__i32_load8_s=a=>(c.__i32_load8_s=Y.H)(a);c.__i32_load8_u=a=>(c.__i32_load8_u=Y.I)(a);c.__i32_load16_s=a=>(c.__i32_load16_s=Y.J)(a);c.__i32_load16_u=a=>(c.__i32_load16_u=Y.K)(a);c.__i32_load=a=>(c.__i32_load=Y.L)(a);c.__f32_load=a=>(c.__f32_load=Y.M)(a);c.__f64_load=a=>(c.__f64_load=Y.N)(a);var ta=(a,b)=>(ta=Y.O)(a,b);
function Z(){function a(){c.calledRun=!0;if(!A){Y.t();c.onRuntimeInitialized?.();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var b=c.postRun.shift();fa.push(b)}ea(fa)}}if(0<H)I=Z;else{if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)ia();ea(ha);0<H?I=Z:c.setStatus?(c.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>c.setStatus(""),1);a()},1)):a()}}
if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.shift()();Z();
