var c;c||(c=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},c),q="./this.program",t=(a,b)=>{throw b;},ba="object"==typeof window,u="function"==typeof importScripts,v="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,w="",z,A,B;
if(v){var fs=require("fs"),C=require("path");w=u?C.dirname(w)+"/":__dirname+"/";z=(a,b)=>{a=a.startsWith("file://")?new URL(a):C.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};B=a=>{a=z(a,!0);a.buffer||(a=new Uint8Array(a));return a};A=(a,b,f)=>{a=a.startsWith("file://")?new URL(a):C.normalize(a);fs.readFile(a,function(e,g){e?f(e):b(g.buffer)})};1<process.argv.length&&(q=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=c);process.on("uncaughtException",
function(a){if(!("unwind"===a||a instanceof D||a.context instanceof D))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",function(a){throw a;});t=(a,b)=>{process.exitCode=a;throw b;};c.inspect=function(){return"[Emscripten Module object]"}}else if(ba||u)u?w=self.location.href:"undefined"!=typeof document&&document.currentScript&&(w=document.currentScript.src),w=0!==w.indexOf("blob:")?w.substr(0,w.replace(/[?#].*/,"").lastIndexOf("/")+1):"",z=a=>{var b=new XMLHttpRequest;
b.open("GET",a,!1);b.send(null);return b.responseText},u&&(B=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),A=(a,b,f)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):f()};e.onerror=f;e.send(null)};var ca=c.print||console.log.bind(console),E=c.printErr||console.warn.bind(console);Object.assign(c,aa);aa=null;c.thisProgram&&(q=c.thisProgram);
c.quit&&(t=c.quit);var F;c.wasmBinary&&(F=c.wasmBinary);var noExitRuntime=c.noExitRuntime||!0;"object"!=typeof WebAssembly&&G("no native wasm support detected");var H,I=!1,da="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ea(a,b,f){var e=b+f;for(f=b;a[f]&&!(f>=e);)++f;if(16<f-b&&a.buffer&&da)return da.decode(a.subarray(b,f));for(e="";b<f;){var g=a[b++];if(g&128){var h=a[b++]&63;if(192==(g&224))e+=String.fromCharCode((g&31)<<6|h);else{var l=a[b++]&63;g=224==(g&240)?(g&15)<<12|h<<6|l:(g&7)<<18|h<<12|l<<6|a[b++]&63;65536>g?e+=String.fromCharCode(g):(g-=65536,e+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else e+=String.fromCharCode(g)}return e}function J(a,b){return a?ea(K,a,b):""}var L,K,M,N;
function fa(){var a=H.buffer;c.HEAP8=L=new Int8Array(a);c.HEAP16=new Int16Array(a);c.HEAP32=M=new Int32Array(a);c.HEAPU8=K=new Uint8Array(a);c.HEAPU16=new Uint16Array(a);c.HEAPU32=N=new Uint32Array(a);c.HEAPF32=new Float32Array(a);c.HEAPF64=new Float64Array(a)}var O,ha=[],ia=[],ja=[];function ka(){var a=c.preRun.shift();ha.unshift(a)}var P=0,Q=null,R=null;
function G(a){if(c.onAbort)c.onAbort(a);a="Aborted("+a+")";E(a);I=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function la(a){return a.startsWith("data:application/octet-stream;base64,")}var S;S="cyth.wasm";if(!la(S)){var ma=S;S=c.locateFile?c.locateFile(ma,w):w+ma}function na(a){try{if(a==S&&F)return new Uint8Array(F);if(B)return B(a);throw"both async and sync fetching of the wasm failed";}catch(b){G(b)}}
function oa(a){if(!F&&(ba||u)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return na(a)});if(A)return new Promise(function(b,f){A(a,function(e){b(new Uint8Array(e))},f)})}return Promise.resolve().then(function(){return na(a)})}
function pa(a,b,f){return oa(a).then(function(e){return WebAssembly.instantiate(e,b)}).then(function(e){return e}).then(f,function(e){E("failed to asynchronously prepare wasm: "+e);G(e)})}
function ta(a,b){var f=S;F||"function"!=typeof WebAssembly.instantiateStreaming||la(f)||f.startsWith("file://")||v||"function"!=typeof fetch?pa(f,a,b):fetch(f,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,a).then(b,function(g){E("wasm streaming compile failed: "+g);E("falling back to ArrayBuffer instantiation");return pa(f,a,b)})})}function D(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function T(a){for(;0<a.length;)a.shift()(c)}function ua(a){this.S=a-24;this.ba=function(b){N[this.S+4>>2]=b};this.Z=function(b){N[this.S+8>>2]=b};this.$=function(){M[this.S>>2]=0};this.Y=function(){L[this.S+12>>0]=0};this.aa=function(){L[this.S+13>>0]=0};this.W=function(b,f){this.X();this.ba(b);this.Z(f);this.$();this.Y();this.aa()};this.X=function(){N[this.S+16>>2]=0}}var va=0,U={};
function wa(){if(!V){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:q||"./this.program"},b;for(b in U)void 0===U[b]?delete a[b]:a[b]=U[b];var f=[];for(b in a)f.push(b+"="+a[b]);V=f}return V}var V,xa=[null,[],[]];function W(a){return 0===a%4&&(0!==a%100||0===a%400)}var ya=[31,29,31,30,31,30,31,31,30,31,30,31],za=[31,28,31,30,31,30,31,31,30,31,30,31];
function Aa(a){for(var b=0,f=0;f<a.length;++f){var e=a.charCodeAt(f);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++f):b+=3}b=Array(b+1);e=b.length;f=0;if(0<e){e=f+e-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(f>=e)break;b[f++]=h}else{if(2047>=h){if(f+1>=e)break;b[f++]=192|h>>6}else{if(65535>=h){if(f+2>=e)break;b[f++]=224|h>>12}else{if(f+3>=e)break;b[f++]=240|h>>18;b[f++]=128|h>>12&63}b[f++]=128|
h>>6&63}b[f++]=128|h&63}}b[f]=0}return b}
function Ba(a,b,f,e){function g(d,k,m){for(d="number"==typeof d?d.toString():d||"";d.length<k;)d=m[0]+d;return d}function h(d,k){return g(d,k,"0")}function l(d,k){function m(qa){return 0>qa?-1:0<qa?1:0}var x;0===(x=m(d.getFullYear()-k.getFullYear()))&&0===(x=m(d.getMonth()-k.getMonth()))&&(x=m(d.getDate()-k.getDate()));return x}function n(d){switch(d.getDay()){case 0:return new Date(d.getFullYear()-1,11,29);case 1:return d;case 2:return new Date(d.getFullYear(),0,3);case 3:return new Date(d.getFullYear(),
0,2);case 4:return new Date(d.getFullYear(),0,1);case 5:return new Date(d.getFullYear()-1,11,31);case 6:return new Date(d.getFullYear()-1,11,30)}}function y(d){var k=d.P;for(d=new Date((new Date(d.R+1900,0,1)).getTime());0<k;){var m=d.getMonth(),x=(W(d.getFullYear())?ya:za)[m];if(k>x-d.getDate())k-=x-d.getDate()+1,d.setDate(1),11>m?d.setMonth(m+1):(d.setMonth(0),d.setFullYear(d.getFullYear()+1));else{d.setDate(d.getDate()+k);break}}m=new Date(d.getFullYear()+1,0,4);k=n(new Date(d.getFullYear(),0,
4));m=n(m);return 0>=l(k,d)?0>=l(m,d)?d.getFullYear()+1:d.getFullYear():d.getFullYear()-1}var r=M[e+40>>2];e={fa:M[e>>2],ea:M[e+4>>2],T:M[e+8>>2],V:M[e+12>>2],U:M[e+16>>2],R:M[e+20>>2],O:M[e+24>>2],P:M[e+28>>2],ha:M[e+32>>2],da:M[e+36>>2],ga:r?J(r):""};f=J(f);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in r)f=f.replace(new RegExp(p,"g"),r[p]);var ra="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),sa="January February March April May June July August September October November December".split(" ");r={"%a":function(d){return ra[d.O].substring(0,3)},"%A":function(d){return ra[d.O]},"%b":function(d){return sa[d.U].substring(0,3)},"%B":function(d){return sa[d.U]},
"%C":function(d){return h((d.R+1900)/100|0,2)},"%d":function(d){return h(d.V,2)},"%e":function(d){return g(d.V,2," ")},"%g":function(d){return y(d).toString().substring(2)},"%G":function(d){return y(d)},"%H":function(d){return h(d.T,2)},"%I":function(d){d=d.T;0==d?d=12:12<d&&(d-=12);return h(d,2)},"%j":function(d){for(var k=0,m=0;m<=d.U-1;k+=(W(d.R+1900)?ya:za)[m++]);return h(d.V+k,3)},"%m":function(d){return h(d.U+1,2)},"%M":function(d){return h(d.ea,2)},"%n":function(){return"\n"},"%p":function(d){return 0<=
d.T&&12>d.T?"AM":"PM"},"%S":function(d){return h(d.fa,2)},"%t":function(){return"\t"},"%u":function(d){return d.O||7},"%U":function(d){return h(Math.floor((d.P+7-d.O)/7),2)},"%V":function(d){var k=Math.floor((d.P+7-(d.O+6)%7)/7);2>=(d.O+371-d.P-2)%7&&k++;if(k)53==k&&(m=(d.O+371-d.P)%7,4==m||3==m&&W(d.R)||(k=1));else{k=52;var m=(d.O+7-d.P-1)%7;(4==m||5==m&&W(d.R%400-1))&&k++}return h(k,2)},"%w":function(d){return d.O},"%W":function(d){return h(Math.floor((d.P+7-(d.O+6)%7)/7),2)},"%y":function(d){return(d.R+
1900).toString().substring(2)},"%Y":function(d){return d.R+1900},"%z":function(d){d=d.da;var k=0<=d;d=Math.abs(d)/60;return(k?"+":"-")+String("0000"+(d/60*100+d%60)).slice(-4)},"%Z":function(d){return d.ga},"%%":function(){return"%"}};f=f.replace(/%%/g,"\x00\x00");for(p in r)f.includes(p)&&(f=f.replace(new RegExp(p,"g"),r[p](e)));f=f.replace(/\0\0/g,"%");p=Aa(f);if(p.length>b)return 0;L.set(p,a);return p.length-1}
var X=[],Y=void 0,Ca=[],Da={a:function(a,b,f,e){G("Assertion failed: "+J(a)+", at: "+[b?J(b):"unknown filename",f,e?J(e):"unknown function"])},c:function(a,b,f){(new ua(a)).W(b,f);va++;throw a;},e:function(){return 0},h:function(){return 0},i:function(){},m:function(){return!0},b:function(){G("")},o:v?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now(),r:function(a,b,f){K.copyWithin(a,b,b+f)},n:function(a){var b=K.length;a>>>=0;if(2147483648<a)return!1;for(var f=1;4>=f;f*=
2){var e=b*(1+.2/f);e=Math.min(e,a+100663296);var g=Math,h=g.min;e=Math.max(a,e);e+=(65536-e%65536)%65536;a:{var l=H.buffer;try{H.grow(h.call(g,2147483648,e)-l.byteLength+65535>>>16);fa();var n=1;break a}catch(y){}n=void 0}if(n)return!0}return!1},p:function(a,b){var f=0;wa().forEach(function(e,g){var h=b+f;g=N[a+4*g>>2]=h;for(h=0;h<e.length;++h)L[g++>>0]=e.charCodeAt(h);L[g>>0]=0;f+=e.length+1});return 0},q:function(a,b){var f=wa();N[a>>2]=f.length;var e=0;f.forEach(function(g){e+=g.length+1});N[b>>
2]=e;return 0},d:function(){return 52},g:function(){return 52},k:function(){return 70},f:function(a,b,f,e){for(var g=0,h=0;h<f;h++){var l=N[b>>2],n=N[b+4>>2];b+=8;for(var y=0;y<n;y++){var r=K[l+y],p=xa[a];0===r||10===r?((1===a?ca:E)(ea(p,0)),p.length=0):p.push(r)}g+=n}N[e>>2]=g;return 0},j:function(a){if(!noExitRuntime){if(c.onExit)c.onExit(a);I=!0}t(a,new D(a))},l:function(a,b,f,e){return Ba(a,b,f,e)}};
(function(){function a(f){f=f.exports;c.asm=f;H=c.asm.s;fa();O=c.asm.N;ia.unshift(c.asm.t);P--;c.monitorRunDependencies&&c.monitorRunDependencies(P);if(0==P&&(null!==Q&&(clearInterval(Q),Q=null),R)){var e=R;R=null;e()}return f}var b={a:Da};P++;c.monitorRunDependencies&&c.monitorRunDependencies(P);if(c.instantiateWasm)try{return c.instantiateWasm(b,a)}catch(f){return E("Module.instantiateWasm callback failed with error: "+f),!1}ta(b,function(f){a(f.instance)});return{}})();
c._memory_alloc=function(){return(c._memory_alloc=c.asm.u).apply(null,arguments)};c._free=function(){return(c._free=c.asm.v).apply(null,arguments)};c._set_error_callback=function(){return(c._set_error_callback=c.asm.w).apply(null,arguments)};c._set_result_callback=function(){return(c._set_result_callback=c.asm.x).apply(null,arguments)};c._run=function(){return(c._run=c.asm.y).apply(null,arguments)};c._BinaryenSizeofLiteral=function(){return(c._BinaryenSizeofLiteral=c.asm.z).apply(null,arguments)};
c._BinaryenSizeofAllocateAndWriteResult=function(){return(c._BinaryenSizeofAllocateAndWriteResult=c.asm.A).apply(null,arguments)};c.__i32_store8=function(){return(c.__i32_store8=c.asm.B).apply(null,arguments)};c.__i32_store16=function(){return(c.__i32_store16=c.asm.C).apply(null,arguments)};c.__i32_store=function(){return(c.__i32_store=c.asm.D).apply(null,arguments)};c.__f32_store=function(){return(c.__f32_store=c.asm.E).apply(null,arguments)};
c.__f64_store=function(){return(c.__f64_store=c.asm.F).apply(null,arguments)};c.__i32_load8_s=function(){return(c.__i32_load8_s=c.asm.G).apply(null,arguments)};c.__i32_load8_u=function(){return(c.__i32_load8_u=c.asm.H).apply(null,arguments)};c.__i32_load16_s=function(){return(c.__i32_load16_s=c.asm.I).apply(null,arguments)};c.__i32_load16_u=function(){return(c.__i32_load16_u=c.asm.J).apply(null,arguments)};c.__i32_load=function(){return(c.__i32_load=c.asm.K).apply(null,arguments)};
c.__f32_load=function(){return(c.__f32_load=c.asm.L).apply(null,arguments)};c.__f64_load=function(){return(c.__f64_load=c.asm.M).apply(null,arguments)};c.UTF8ToString=J;
c.addFunction=function(a,b){if(!Y){Y=new WeakMap;var f=O.length;if(Y)for(var e=0;e<0+f;e++){var g=e;var h=X[g];h||(g>=X.length&&(X.length=g+1),X[g]=h=O.get(g));(g=h)&&Y.set(g,e)}}if(f=Y.get(a)||0)return f;if(Ca.length)f=Ca.pop();else{try{O.grow(1)}catch(n){if(!(n instanceof RangeError))throw n;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}f=O.length-1}try{e=f,O.set(e,a),X[e]=O.get(e)}catch(n){if(!(n instanceof TypeError))throw n;if("function"==typeof WebAssembly.Function){e=WebAssembly.Function;
g={i:"i32",j:"i32",f:"f32",d:"f64",p:"i32"};h={parameters:[],results:"v"==b[0]?[]:[g[b[0]]]};for(var l=1;l<b.length;++l)h.parameters.push(g[b[l]]),"j"===b[l]&&h.parameters.push("i32");b=new e(h,a)}else{e=[1];g=b.slice(0,1);b=b.slice(1);h={i:127,p:127,j:126,f:125,d:124};e.push(96);l=b.length;128>l?e.push(l):e.push(l%128|128,l>>7);for(l=0;l<b.length;++l)e.push(h[b[l]]);"v"==g?e.push(0):e.push(1,h[g]);b=[0,97,115,109,1,0,0,0,1];g=e.length;128>g?b.push(g):b.push(g%128|128,g>>7);b.push.apply(b,e);b.push(2,
7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f}e=f;O.set(e,b);X[e]=O.get(e)}Y.set(a,f);return f};var Z;R=function Ea(){Z||Fa();Z||(R=Ea)};
function Fa(){function a(){if(!Z&&(Z=!0,c.calledRun=!0,!I)){T(ia);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var b=c.postRun.shift();ja.unshift(b)}T(ja)}}if(!(0<P)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)ka();T(ha);0<P||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},1);a()},1)):a())}}
if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();Fa();
